### ISSUE TITLE
Ember-cli-responsive and IE9

### ISSUE THREAD

**Issue by florent-blanvillain** [AVCEngineering/ember-cli-responsive#5]
Under IE9, I get this error message: `SCRIPT5007: Object expected`.

It corresponds to this line : 

```
App.responsive({ // ember-cli-responsive plugin conf
// ....
```

**Comment by AVCEngineering** [comment]
@florent-blanvillain I'll take a look but in the meantime try importing matchmedia from bower_components

``` js
app.import('bower_components/matchMedia/matchMedia.js');
```

**Comment by AVCEngineering** [comment]
Also which version are you using?

**Comment by florent-blanvillain** [comment]
Sorry I've been pretty busy..

I use `"ember-cli-responsive": "^0.1.3"`.

And your workaround works, thanks !

**Comment by AVCEngineering** [comment]
Hurray! not a bug :+1:
